### ISSUE TITLE
stuck on loading

### ISSUE THREAD

**Issue by nadavvin** [z0u/cargo#7]
It stuck on the second loading image.

python cannot load some modules.

see logs:

http://pastebin.ca/2696064
http://pastebin.ca/2696068

**Comment by z0u** [comment]
Hi,

Are you trying to run this from the git repository? Cargo uses the [Blender Adventure Toolkit](https://github.com/oasakfu/bat) library (which was written for Cargo), which you need to initialise as a submodule. Try running this from the `cargo` root directory:

``` bash
git submodule update --init
```

I see this is missing from the `README.md`. I should add it!

**Comment by z0u** [comment]
Or you can if you like; I'd gladly accept a pull request with improved instructions.

**Comment by z0u** [comment]
Just wanted to check if this fixed it for you?

**Comment by nadavvin** [comment]
it work thanks.
